//! Canonical RVF compiler for progressively disclosed context artifacts.

use crate::{ServiceError, ServiceResult};
use rvm_context::{
    ContextProfile, DerivedView, ProfileTrust, ProfileView, ProgressiveView, Revision,
    VerifiedContextProfile, MAX_RVF_BYTES,
};
use rvm_rvf::format::{SEG_TYPE_MANIFEST, SEG_TYPE_META, SEG_TYPE_PROFILE, SEG_TYPE_WITNESS};
use rvm_rvf::{
    content_hash, sha256, SegmentHeader, SEGMENT_HEADER_SIZE, SEGMENT_MAGIC, SEGMENT_VERSION,
};

const CONTEXT_PAYLOAD_SEGMENT: u8 = SEG_TYPE_META;
const CHECKSUM_SHA256_128: u8 = 2;

/// One generated abstract or overview with complete provenance.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct DerivedContextView {
    view: ProgressiveView,
    payload: Vec<u8>,
    provenance: DerivedView,
}

impl DerivedContextView {
    /// Construct one generated representation.
    ///
    /// # Errors
    ///
    /// Refuses `content`, which is authoritative input rather than a derived
    /// representation.
    pub fn new(
        view: ProgressiveView,
        payload: Vec<u8>,
        provenance: DerivedView,
    ) -> ServiceResult<Self> {
        if view == ProgressiveView::Content {
            return Err(ServiceError::CorruptState(
                "content cannot be supplied as a derived view",
            ));
        }
        Ok(Self {
            view,
            payload,
            provenance,
        })
    }

    /// Generated representation selector.
    #[must_use]
    pub const fn view(&self) -> ProgressiveView {
        self.view
    }

    /// Exact generated bytes committed by the profile.
    #[must_use]
    pub fn payload(&self) -> &[u8] {
        &self.payload
    }

    /// Complete generation provenance.
    #[must_use]
    pub const fn provenance(&self) -> DerivedView {
        self.provenance
    }
}

/// Inputs for one independently verifiable context RVF.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ContextCompileRequest {
    content: Vec<u8>,
    content_segment_type: u8,
    metadata: Option<Vec<u8>>,
    derived: Vec<DerivedContextView>,
}

impl ContextCompileRequest {
    /// Start a non-executable context artifact using canonical RVF `META`
    /// storage for the authoritative content bytes.
    #[must_use]
    pub fn data(content: Vec<u8>) -> Self {
        Self {
            content,
            content_segment_type: CONTEXT_PAYLOAD_SEGMENT,
            metadata: None,
            derived: Vec::new(),
        }
    }

    /// Start a context artifact whose content uses an existing RVF segment
    /// type, including canonical WASM, eBPF, or kernel types for skills.
    ///
    /// # Errors
    ///
    /// Refuses structural segment types that cannot be authoritative content.
    pub fn with_content_segment(content: Vec<u8>, segment_type: u8) -> ServiceResult<Self> {
        if matches!(
            segment_type,
            0 | SEG_TYPE_MANIFEST | SEG_TYPE_PROFILE | SEG_TYPE_WITNESS
        ) {
            return Err(ServiceError::CorruptState(
                "invalid RVF content segment type",
            ));
        }
        Ok(Self {
            content,
            content_segment_type: segment_type,
            metadata: None,
            derived: Vec::new(),
        })
    }

    /// Add canonical non-authoritative RVF metadata, such as capability
    /// declarations for an executable skill.
    #[must_use]
    pub fn metadata(mut self, metadata: Vec<u8>) -> Self {
        self.metadata = Some(metadata);
        self
    }

    /// Add an abstract or overview representation.
    ///
    /// Duplicate selectors are rejected by [`RvfContextCompiler::compile`].
    #[must_use]
    pub fn derived_view(mut self, view: DerivedContextView) -> Self {
        self.derived.push(view);
        self
    }
}

/// A complete artifact that passed the same RVF/profile verifier used on
/// service ingress.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct CompiledContextArtifact {
    rvf: Vec<u8>,
    identity: Revision,
    profile: ContextProfile,
}

impl CompiledContextArtifact {
    /// Complete canonical RVF byte stream.
    #[must_use]
    pub fn rvf(&self) -> &[u8] {
        &self.rvf
    }

    /// SHA-256 identity suitable for a pinned `ruv://` revision.
    #[must_use]
    pub const fn identity(&self) -> Revision {
        self.identity
    }

    /// Profile whose payload is embedded in the RVF.
    #[must_use]
    pub const fn profile(&self) -> &ContextProfile {
        &self.profile
    }

    /// Consume the result and return the complete RVF bytes.
    #[must_use]
    pub fn into_rvf(self) -> Vec<u8> {
        self.rvf
    }
}

/// Deterministic compiler that emits no private RVF discriminants.
#[derive(Debug, Clone, Copy, Default)]
pub struct RvfContextCompiler;

impl RvfContextCompiler {
    /// Compile and immediately verify a context artifact.
    ///
    /// Segment ordinals are deterministic, every profile view is digest-bound,
    /// and the returned identity covers the complete RVF byte stream.
    ///
    /// # Errors
    ///
    /// Refuses duplicate views, invalid provenance, oversized output, invalid
    /// segment types, or any artifact that fails RVF/profile self-verification.
    pub fn compile(request: ContextCompileRequest) -> ServiceResult<CompiledContextArtifact> {
        let ContextCompileRequest {
            content,
            content_segment_type,
            metadata,
            mut derived,
        } = request;
        derived.sort_by_key(DerivedContextView::view);
        if derived.windows(2).any(|pair| pair[0].view == pair[1].view) {
            return Err(ServiceError::CorruptState("duplicate progressive view"));
        }

        let mut rvf = Vec::new();
        let mut next_segment_id = 1_u64;
        if let Some(metadata) = metadata {
            append_segment(&mut rvf, SEG_TYPE_META, next_segment_id, &metadata)?;
            next_segment_id = checked_segment_id(next_segment_id)?;
        }
        let content_segment_id = next_segment_id;
        append_segment(&mut rvf, content_segment_type, content_segment_id, &content)?;
        next_segment_id = checked_segment_id(next_segment_id)?;

        let content_digest = Revision::from_bytes(sha256(&content));
        let mut profile_views = vec![ProfileView::content(content_segment_id, content_digest)
            .map_err(|_| ServiceError::CorruptState("invalid content profile"))?];
        for view in derived {
            let segment_id = next_segment_id;
            append_segment(&mut rvf, CONTEXT_PAYLOAD_SEGMENT, segment_id, &view.payload)?;
            next_segment_id = checked_segment_id(next_segment_id)?;
            profile_views.push(
                ProfileView::derived(
                    view.view,
                    segment_id,
                    Revision::from_bytes(sha256(&view.payload)),
                    view.provenance,
                )
                .map_err(|_| ServiceError::CorruptState("invalid derived-view profile"))?,
            );
        }
        let profile = ContextProfile::new(profile_views)
            .map_err(|_| ServiceError::CorruptState("invalid context profile"))?;
        append_segment(
            &mut rvf,
            SEG_TYPE_PROFILE,
            next_segment_id,
            &profile.to_bytes(),
        )?;
        next_segment_id = checked_segment_id(next_segment_id)?;
        append_segment(
            &mut rvf,
            SEG_TYPE_MANIFEST,
            next_segment_id,
            b"ruv.context/1",
        )?;

        if rvf.len() > MAX_RVF_BYTES {
            return Err(ServiceError::CorruptState(
                "compiled context RVF exceeds ingress limit",
            ));
        }
        let identity = Revision::from_bytes(sha256(&rvf));
        let verified =
            VerifiedContextProfile::from_rvf(&rvf, identity, ProfileTrust::PinnedIdentity, &[])
                .map_err(|_| {
                    ServiceError::CorruptState("compiled context RVF failed verification")
                })?;
        if verified.profile() != &profile {
            return Err(ServiceError::CorruptState(
                "compiled context profile changed during verification",
            ));
        }
        Ok(CompiledContextArtifact {
            rvf,
            identity,
            profile,
        })
    }
}

fn checked_segment_id(segment_id: u64) -> ServiceResult<u64> {
    segment_id
        .checked_add(1)
        .ok_or(ServiceError::CorruptState("RVF segment ID overflow"))
}

fn append_segment(
    output: &mut Vec<u8>,
    segment_type: u8,
    segment_id: u64,
    payload: &[u8],
) -> ServiceResult<()> {
    let payload_length = u64::try_from(payload.len())
        .map_err(|_| ServiceError::CorruptState("RVF segment is too large"))?;
    let total = SEGMENT_HEADER_SIZE
        .checked_add(payload.len())
        .ok_or(ServiceError::CorruptState("RVF segment length overflow"))?;
    let padded = total
        .checked_add(SEGMENT_HEADER_SIZE - 1)
        .map(|value| value / SEGMENT_HEADER_SIZE * SEGMENT_HEADER_SIZE)
        .ok_or(ServiceError::CorruptState("RVF padding overflow"))?;
    let alignment_pad = u32::try_from(padded - total)
        .map_err(|_| ServiceError::CorruptState("RVF padding is too large"))?;
    let header = SegmentHeader {
        magic: SEGMENT_MAGIC,
        version: SEGMENT_VERSION,
        seg_type: segment_type,
        flags: 0,
        segment_id,
        payload_length,
        timestamp_ns: 0,
        checksum_algo: CHECKSUM_SHA256_128,
        compression: 0,
        reserved_0: 0,
        reserved_1: 0,
        content_hash: content_hash(CHECKSUM_SHA256_128, payload),
        uncompressed_len: 0,
        alignment_pad,
    };
    output.extend_from_slice(&header.to_bytes());
    output.extend_from_slice(payload);
    output.resize(
        output
            .len()
            .checked_add(usize::try_from(alignment_pad).unwrap_or(0))
            .ok_or(ServiceError::CorruptState("RVF output length overflow"))?,
        0,
    );
    Ok(())
}

#[cfg(test)]
mod tests {
    // These tests exercise the compiler's mandatory self-verification path.
    use super::*;

    fn provenance(source: Revision) -> DerivedView {
        DerivedView::new(
            source,
            Revision::from_bytes([2; 32]),
            Revision::from_bytes([3; 32]),
            Revision::from_bytes([4; 32]),
            Revision::from_bytes([5; 32]),
        )
        .unwrap()
    }

    #[test]
    fn compiler_round_trips_every_view_and_rejects_tampering() {
        let content = b"authoritative content".to_vec();
        let source = Revision::from_bytes(sha256(&content));
        let request = ContextCompileRequest::data(content.clone())
            .derived_view(
                DerivedContextView::new(
                    ProgressiveView::Abstract,
                    b"short".to_vec(),
                    provenance(source),
                )
                .unwrap(),
            )
            .derived_view(
                DerivedContextView::new(
                    ProgressiveView::Overview,
                    b"structured overview".to_vec(),
                    provenance(source),
                )
                .unwrap(),
            );
        let artifact = RvfContextCompiler::compile(request).unwrap();
        let verified = VerifiedContextProfile::from_rvf(
            artifact.rvf(),
            artifact.identity(),
            ProfileTrust::PinnedIdentity,
            &[],
        )
        .unwrap();
        assert_eq!(
            verified
                .payload(artifact.rvf(), ProgressiveView::Content)
                .unwrap(),
            content
        );
        assert_eq!(
            verified
                .payload(artifact.rvf(), ProgressiveView::Overview)
                .unwrap(),
            b"structured overview"
        );

        let mut tampered = artifact.into_rvf();
        tampered[SEGMENT_HEADER_SIZE] ^= 1;
        assert!(VerifiedContextProfile::from_rvf(
            &tampered,
            Revision::from_bytes(sha256(&tampered)),
            ProfileTrust::PinnedIdentity,
            &[],
        )
        .is_err());
    }
}
