//! Cross-repo receipt anchoring for the RVM witness chain (ADR-156).
//!
//! Consumes the witness/receipt contract extracted from ruflo ADR-322C
//! (`ruflo` `v3/docs/spec/witness-receipt-contract.md`, tracked by
//! `ruvnet/ruflo#3066` / `ruvnet/rvm#35`): verifies a
//! `ruflo.flywheel-receipt/v1` evaluation receipt end to end —
//! JCS canonicalization, SHA-256 content IDs, Ed25519 over
//! domain-prefixed bytes, statistical recomputation — and anchors a
//! commitment to it as an ADR-134 witness record.
//!
//! # What is contract and what is proposal
//!
//! - The **receipt** format, its verification algorithm, and the signing
//!   domain `ruflo/flywheel-receipt/v1` are ADR-322C contract. ADR-322C
//!   defines exactly **two** Ed25519 signing domains — the receipt domain
//!   and `ruflo/flywheel-ledger-head/v1` (specified, unimplemented on
//!   ruflo `main`) — which is why this crate anchors the *receipt* and
//!   not the ledger head (contract gap G2; checklist C3).
//! - The **anchor record** (`ruflo.anchor-record/v1`), its
//!   `assuranceLevel` field, and the `ruflo/flywheel-anchor/v1` domain
//!   are a **`PROPOSED-EXTENSION`** (contract §9): a PIR proposal pending
//!   ruflo review, not an established contract. Code in [`anchor`] says
//!   so at every surface.
//!
//! # Version policy
//!
//! Pins are **`schemaVersion` + `gateVersion` strings**
//! ([`receipt::SUPPORTED_SCHEMA_VERSION`],
//! [`receipt::SUPPORTED_GATE_VERSION`]), never ruflo git SHAs — a SHA pin
//! would couple this repo's release cadence to ruflo's commit history
//! (checklist F1). Unrecognized versions are refused, never best-effort
//! parsed (F2), and a gate change is never applied retroactively (F3):
//! this verifier refuses receipts under gates it cannot recompute.
//!
//! # Assurance honesty (ADR-285)
//!
//! Receipts are service-side artifacts. Anchoring one into the
//! hypervisor-side witness chain records provenance; it does **not**
//! confer hypervisor guarantees. [`anchor::anchor_verified_receipt`]
//! stamps `service-side` unconditionally — there is no parameter through
//! which a caller could claim otherwise for a foreign record.
//!
//! # `no_std`
//!
//! `no_std` with `alloc`: receipts are JSON documents, so parsing and
//! canonicalization allocate. Ed25519 verification uses the same
//! `ed25519-dalek` (default-features off) already trusted by `rvm-rvf`.

#![no_std]
#![forbid(unsafe_code)]
#![deny(missing_docs)]
#![deny(clippy::all)]
#![warn(clippy::pedantic)]

extern crate alloc;

#[cfg(test)]
extern crate std;

pub mod anchor;
pub mod jcs;
pub mod receipt;
pub mod stats;

pub use anchor::{
    anchor_verified_receipt, witness_matches_anchor, AnchorError, AnchorOutcome, AnchorRecordV1,
    AssuranceLevel, ANCHOR_SCHEMA_VERSION,
};
pub use jcs::{Json, JsonError};
pub use receipt::{
    content_id, verify_receipt, EvidenceGrade, ReceiptError, TermGrade, VerifiedReceipt,
    RECEIPT_DOMAIN, SUPPORTED_GATE_VERSION, SUPPORTED_SCHEMA_VERSION,
};

#[cfg(test)]
mod conformance {
    //! Conformance tests against the merged ruflo contract fixtures.
    //!
    //! Fixtures in `fixtures/` are copied **verbatim** from
    //! `ruvnet/ruflo` `v3/docs/spec/examples/` at merge commit
    //! `df0c9821984b2b0f76ea0ea6eb6cfe5abda5bd54` (PR ruvnet/ruflo#3067).
    //! They were generated by ruflo's real implementation, so a pass here
    //! is producer/verifier interop, not self-agreement. SHA-256 of the
    //! copies:
    //!
    //! - `receipt-accepted.example.json`
    //!   `fa90341963ac7833b889f8ed5db50d81ebca9af71ce3fc5e05d1f344b9e05167`
    //! - `receipt-bootstrap-reference.example.json`
    //!   `4d2fd409590373a2a2cf112805ba33e4537251a8d0b5cd4a541d773e2ac19fda`
    //! - `anchor-record.example.json`
    //!   `463d19f96ede40febd3ad0f7eea9e16e9ec7e53d4f2da4506e73c1bc4ecf355b`
    //!
    //! Checklist references (`conformance-checklist.md`) are quoted per
    //! test. Both receipt fixtures expire at 2026-08-20T00:00:00.000Z,
    //! so verification time is fixed inside their validity window.

    use super::*;
    use alloc::string::String;
    use alloc::vec::Vec;
    use rvm_witness::{verify_chain, WitnessLog};

    const ACCEPTED: &str = include_str!("../fixtures/receipt-accepted.example.json");
    const BOOTSTRAP_REFERENCE: &str =
        include_str!("../fixtures/receipt-bootstrap-reference.example.json");
    const ANCHOR_EXAMPLE: &str = include_str!("../fixtures/anchor-record.example.json");

    /// Verification instant inside both fixtures' validity windows.
    const NOW: &str = "2026-08-19T12:00:00.000Z";

    #[allow(clippy::cast_possible_truncation)] // byte extraction in the local base64
    fn fixture_signer(text: &str) -> [u8; 32] {
        // Trust exactly the fixture's own signer, extracted from its PEM;
        // trusting a key is the caller's decision, so tests make it
        // explicitly.
        let doc = Json::parse(text).unwrap();
        let pem = doc
            .get("signature")
            .and_then(|s| s.get("publicKeyPem"))
            .and_then(Json::as_str)
            .unwrap();
        let body: String = pem.lines().filter(|l| !l.starts_with("-----")).collect();
        let mut der = Vec::new();
        // Decode via the same base64 the verifier uses, indirectly: parse
        // through a minimal local decode to avoid exposing internals.
        let table = |b: u8| -> u32 {
            match b {
                b'A'..=b'Z' => u32::from(b - b'A'),
                b'a'..=b'z' => u32::from(b - b'a') + 26,
                b'0'..=b'9' => u32::from(b - b'0') + 52,
                b'+' => 62,
                b'/' => 63,
                _ => panic!("bad base64 in fixture"),
            }
        };
        for chunk in body.as_bytes().chunks(4) {
            let pad = chunk.iter().rev().take_while(|&&b| b == b'=').count();
            let mut acc: u32 = 0;
            for &b in &chunk[..4 - pad] {
                acc = (acc << 6) | table(b);
            }
            acc <<= 6 * pad as u32;
            der.push((acc >> 16) as u8);
            if pad < 2 {
                der.push((acc >> 8) as u8);
            }
            if pad < 1 {
                der.push(acc as u8);
            }
        }
        let mut key = [0u8; 32];
        key.copy_from_slice(&der[12..44]);
        key
    }

    /// A1/A6/B5: the accepted fixture — produced and signed by ruflo's
    /// implementation — verifies end to end: structure, content IDs,
    /// signature over `UTF8(domain) || 0x00 || JCS(payload)`, and the
    /// statistical recomputation.
    #[test]
    fn accepted_fixture_verifies() {
        let signer = fixture_signer(ACCEPTED);
        let verified = verify_receipt(ACCEPTED, &[signer], &[], NOW).unwrap();
        assert!(verified.accepted);
        assert_eq!(verified.schema_version, SUPPORTED_SCHEMA_VERSION);
        assert_eq!(verified.gate_version, SUPPORTED_GATE_VERSION);
        assert_eq!(verified.signer_public_key, signer);
        // Every authorizing term carries a grade (B9).
        assert!(!verified.term_grades.is_empty());
    }

    /// B5: the bootstrap-reference fixture is the discriminating one —
    /// its heterogeneous deltas expose a wrong seed slice, byte order,
    /// or LCG constants. The recomputation must reproduce
    /// `0.100428571429`, `1`, `0.0489`, `accepted = true` exactly, which
    /// [`verify_receipt`] checks byte-for-byte before returning Ok.
    #[test]
    fn bootstrap_reference_statistics_recompute() {
        let signer = fixture_signer(BOOTSTRAP_REFERENCE);
        let verified = verify_receipt(BOOTSTRAP_REFERENCE, &[signer], &[], NOW).unwrap();
        assert!(verified.accepted);
        // The checklist's published expectations, asserted directly
        // against the fixture so a fixture drift is caught loudly.
        let doc = Json::parse(BOOTSTRAP_REFERENCE).unwrap();
        let statistics = doc.get("payload").unwrap().get("statistics").unwrap();
        assert_eq!(
            statistics.get("relativeLift").and_then(Json::as_str),
            Some("0.100428571429")
        );
        assert_eq!(
            statistics.get("pairedBootstrapDeltaCILow95").and_then(Json::as_str),
            Some("0.0489")
        );
        assert_eq!(
            statistics.get("seedHex").and_then(Json::as_str),
            Some("167c9185d76163dfa69ae57c11af813669a6353abcb49d7af673acf918f3a7c3")
        );
    }

    /// B1: altering any byte of the canonical record fails verification —
    /// flipping one score yields a receipt content ID mismatch.
    #[test]
    fn tampered_fixture_is_rejected() {
        let tampered = ACCEPTED.replacen("\"0.08\"", "\"0.09\"", 1);
        assert_ne!(tampered, ACCEPTED, "tamper target must exist in fixture");
        let signer = fixture_signer(ACCEPTED);
        let err = verify_receipt(&tampered, &[signer], &[], NOW).unwrap_err();
        assert_eq!(err, ReceiptError::ContentIdMismatch("receipt"));
    }

    /// A1 / gap G3: an unknown payload field is rejected by the field
    /// whitelist, the enforcement ADR-322C requires and ruflo's own
    /// verifier historically lacked (ruflo#3068/#3070).
    #[test]
    fn unknown_field_is_rejected() {
        let injected = ACCEPTED.replacen(
            "\"schemaVersion\"",
            "\"smuggled\": true, \"schemaVersion\"",
            1,
        );
        assert_ne!(injected, ACCEPTED);
        let signer = fixture_signer(ACCEPTED);
        let err = verify_receipt(&injected, &[signer], &[], NOW).unwrap_err();
        assert_eq!(err, ReceiptError::UnknownField(String::from("smuggled")));
    }

    /// The hardened schema bound: `signatureBase64` must match
    /// `^[A-Za-z0-9+/]{86}==$` exactly — an oversized signature is
    /// refused before any cryptography runs.
    #[test]
    fn oversized_signature_is_rejected() {
        let doc = Json::parse(ACCEPTED).unwrap();
        let sig = doc
            .get("signature")
            .and_then(|s| s.get("signatureBase64"))
            .and_then(Json::as_str)
            .unwrap();
        // Grow the base64 body past one Ed25519 signature.
        let oversized_sig = {
            let mut s = String::from(&sig[..86]);
            s.push_str("AAAA==");
            s
        };
        let oversized = ACCEPTED.replacen(sig, &oversized_sig, 1);
        assert_ne!(oversized, ACCEPTED);
        let signer = fixture_signer(ACCEPTED);
        let err = verify_receipt(&oversized, &[signer], &[], NOW).unwrap_err();
        assert_eq!(
            err,
            ReceiptError::SignatureMalformed("signatureBase64 outside ^[A-Za-z0-9+/]{86}==$")
        );
    }

    /// B3: a cryptographically valid signature from a signer outside the
    /// trusted set is refused, not merely flagged.
    #[test]
    fn untrusted_signer_is_refused() {
        let err = verify_receipt(ACCEPTED, &[[0x42u8; 32]], &[], NOW).unwrap_err();
        assert_eq!(err, ReceiptError::UntrustedSigner);
    }

    /// B4: a signature whose domain is not the exact receipt domain is
    /// refused — the replay defence between ruflo signing domains.
    #[test]
    fn wrong_domain_is_refused() {
        let swapped = ACCEPTED.replacen(
            "\"domain\": \"ruflo/flywheel-receipt/v1\"",
            "\"domain\": \"ruflo/flywheel-ledger-head/v1\"",
            1,
        );
        assert_ne!(swapped, ACCEPTED);
        let signer = fixture_signer(ACCEPTED);
        let err = verify_receipt(&swapped, &[signer], &[], NOW).unwrap_err();
        assert_eq!(
            err,
            ReceiptError::SignatureMalformed("domain is not the receipt domain")
        );
    }

    /// B2: reordering transport keys does not change validity — the same
    /// receipt with its two top-level members swapped still verifies.
    #[test]
    fn key_reordering_is_canonicalization_neutral() {
        let doc = Json::parse(ACCEPTED).unwrap();
        let pairs = doc.as_obj().unwrap();
        let reversed: Vec<(String, Json)> = pairs.iter().rev().cloned().collect();
        // Re-serialize with reversed member order (non-canonical JSON).
        let mut transport = String::from("{");
        for (i, (k, v)) in reversed.iter().enumerate() {
            if i > 0 {
                transport.push(',');
            }
            transport.push('"');
            transport.push_str(k);
            transport.push_str("\":");
            transport.push_str(&v.canonicalize());
        }
        transport.push('}');
        let signer = fixture_signer(ACCEPTED);
        verify_receipt(&transport, &[signer], &[], NOW).unwrap();
    }

    /// B8: an expired receipt is refused. Both fixtures expire at
    /// 2026-08-20T00:00:00.000Z.
    #[test]
    fn expired_receipt_is_refused() {
        let signer = fixture_signer(ACCEPTED);
        let err =
            verify_receipt(ACCEPTED, &[signer], &[], "2026-08-20T00:00:00.000Z").unwrap_err();
        assert_eq!(err, ReceiptError::Expired);
    }

    /// F2: an unrecognized `schemaVersion` is refused, never best-effort
    /// parsed.
    #[test]
    fn unrecognized_schema_version_is_refused() {
        let bumped = ACCEPTED.replacen(
            "ruflo.flywheel-receipt/v1",
            "ruflo.flywheel-receipt/v2",
            1,
        );
        let signer = fixture_signer(ACCEPTED);
        let err = verify_receipt(&bumped, &[signer], &[], NOW).unwrap_err();
        assert_eq!(err, ReceiptError::UnsupportedSchemaVersion);
    }

    /// C3/C4: anchoring commits to the RECEIPT (the record whose
    /// signature is implemented), stamps `service-side` unconditionally,
    /// and the emitted witness record binds the anchor commitment inside
    /// a chain that still verifies end to end (C1).
    #[test]
    fn verified_receipt_anchors_into_witness_chain() {
        let signer = fixture_signer(ACCEPTED);
        let verified = verify_receipt(ACCEPTED, &[signer], &[], NOW).unwrap();

        let log: WitnessLog<16> = WitnessLog::new();
        let outcome = anchor_verified_receipt(
            &log,
            &verified,
            "rvm-witness/pir-acceptance",
            NOW,
            7,
            1_000,
        )
        .unwrap();

        // The anchored content ID is the receipt's, and the assurance
        // level cannot be anything but service-side.
        assert_eq!(
            outcome.record.anchored_content_id,
            content_id(&verified.receipt_id)
        );
        assert_eq!(outcome.record.assurance_level, AssuranceLevel::ServiceSide);
        assert_eq!(outcome.record.anchored_schema_version, SUPPORTED_SCHEMA_VERSION);

        // The witness record binds the anchor record's commitment and the
        // chain verifies.
        let mut records = [rvm_types::WitnessRecord::zeroed(); 16];
        let copied = log.snapshot(&mut records);
        assert_eq!(copied, 1);
        assert!(witness_matches_anchor(&records[0], &outcome.record));
        assert!(verify_chain(&records[..copied]).is_ok());
    }

    /// §9: the `PROPOSED-EXTENSION` anchor-record example from the spec
    /// parses, and a record rebuilt from its fields reproduces its exact
    /// canonical form — shape agreement with the placeholder schema.
    #[test]
    fn anchor_record_example_shape_agrees() {
        let doc = Json::parse(ANCHOR_EXAMPLE).unwrap();
        let payload = doc.get("payload").unwrap();
        let chain = payload.get("chain").unwrap();
        let rebuilt = AnchorRecordV1 {
            anchored_content_id: String::from(
                payload.get("anchoredContentId").and_then(Json::as_str).unwrap(),
            ),
            anchored_schema_version: String::from(
                payload
                    .get("anchoredSchemaVersion")
                    .and_then(Json::as_str)
                    .unwrap(),
            ),
            chain_id: String::from(chain.get("chainId").and_then(Json::as_str).unwrap()),
            position: u64::try_from(chain.get("position").and_then(Json::as_int).unwrap())
                .unwrap(),
            assurance_level: AssuranceLevel::ServiceSide,
            anchored_at: String::from(payload.get("anchoredAt").and_then(Json::as_str).unwrap()),
        };
        assert_eq!(rebuilt.canonical_payload(), payload.canonicalize());
    }

    /// B9: a `trusted-assertion` term with an attestor outside the
    /// approved set blocks the "independently verified" label without
    /// failing verification outright.
    #[test]
    fn unapproved_assertion_blocks_independent_verification() {
        let doc = Json::parse(ACCEPTED).unwrap();
        let has_assertion = doc
            .get("payload")
            .and_then(|p| p.get("termVerification"))
            .and_then(Json::as_arr)
            .is_some_and(|entries| {
                entries.iter().any(|e| {
                    e.get("verification").and_then(Json::as_str) == Some("trusted-assertion")
                })
            });
        let signer = fixture_signer(ACCEPTED);
        let verified = verify_receipt(ACCEPTED, &[signer], &[], NOW).unwrap();
        if has_assertion {
            // No approved attestors were supplied, so the label must be
            // withheld.
            assert!(!verified.independently_verified);
        } else {
            assert!(verified.independently_verified);
        }
    }
}
